// auto generated by configure
#ifndef SRS_AUTO_HEADER_HPP
#define SRS_AUTO_HEADER_HPP

#define SRS_AUTO_FFMPEG_TOOL
#define SRS_AUTO_FFMPEG_STUB
#define SRS_AUTO_TRANSCODE

#define SRS_AUTO_VERBOSE
#define SRS_AUTO_INFO
#define SRS_AUTO_TRACE

#endif


